name: Fake CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo build app && sleep 10
    - run: echo 'lint app' && sleep 1
    - run: echo 'test app' && sleep 10
